apiVersion: v1
kind: Service
metadata:
  labels:
    app: cdmi-pen
    component: aws-pen-prod
  name: aws-pen-prod
  namespace: edu-pen
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30891
  selector:
    app: cdmi-pen
    component: aws-pen-prod
    tier: backend
  sessionAffinity: None
  type: NodePort