apiVersion: v1
kind: Service
metadata:
  labels:
    app: cdmi-pen
    component: aws-pen-dev
  name: aws-pen-dev
  namespace: edu-pen
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30861
  selector:
    app: cdmi-pen
    component: aws-pen-dev
    tier: backend
  sessionAffinity: None
  type: NodePort